targets:
  $default:
    builders:
      flutter_gen_runner|flutter_gen_runner:
        options:
          output_dir: lib/gen/
          line_length: 80
          integrations:
            flutter_svg: false
            flare_flutter: false
            rive: false
            lottie: false
